### ISSUE TITLE
Warning! .env

### ISSUE THREAD

**Issue by swe-rahmatulloh** [mirafzal114/AiTeacher#1]
assalomu alekum! Mirafzal aka .env file productionga chiqib ketibdi, ichidagi key ham ko'rinib turibdi! Bu Agar xato bo'lsa to'g'rilash kerak. 

![image](https://github.com/mirafzal114/AiTeacher/assets/128359200/2e73d0a2-5572-4753-a830-635ed6d45e71)

**Comment by mirafzalswe** [comment]
Valekum assalom u yerda atedan qilingan 
opanAi dan ozilar api key olib qoyb ishlatishilar uchun 
chunki api checklangar zaprolsar beradi
